name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} > ./app/.env
        echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> ./app/.env

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Authenticate Docker with Artifact Registry
      run: |
        gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
        cat ~/.docker/config.json

    - name: Build and push Docker image
      run: |     
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FASTAPI_REPO }}/${{ secrets.FASTAPI_APP }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FASTAPI_REPO }}/${{ secrets.FASTAPI_APP }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.FASTAPI_APP }} \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FASTAPI_REPO }}/${{ secrets.FASTAPI_APP }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
