name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Enable Service Usage API
      run: |
        echo "Enabling Service Usage API..."
        gcloud services enable serviceusage.googleapis.com

    - name: Enable Cloud Resource Manager API
      run: |
        echo "Enabling Cloud Resource Manager API..."
        gcloud services enable cloudresourcemanager.googleapis.com

    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Verify active account
      run: |
        echo "Checking active account..."
        gcloud auth list

    - name: Create .env file
      run: |
        echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} > ./app/.env
        echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> ./app/.env

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Verify IAM Policy
      run: |
        echo "Checking IAM Policy for the service account..."
        gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
          --flatten="bindings[].members" \
          --format="table(bindings.role)" \
          --filter="bindings.members:serviceAccount:react-fastapi-back-app-key@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

    - name: Build and push Docker image
      run: |     
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FASTAPI_REPO }}/${{ secrets.FASTAPI_APP }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FASTAPI_REPO }}/${{ secrets.FASTAPI_APP }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.FASTAPI_APP }} \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FASTAPI_REPO }}/${{ secrets.FASTAPI_APP }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
